const fruits = [
  {id:"fruit-01",product: 'apple',price: 0.5,image: '/Images/apple.jpeg',quantity: 1,}, 
  {id:"fruit-02",product: 'orange',price: 0.7,image: '/Images/orange.jpeg',quantity: 1,},
  {id:"fruit-03",product: 'banana',price: 0.8,image: '/Images/banana.jpeg',quantity: 1,},
  {id:"fruit-04",product: 'pineapple',price: 1.5,image: '/Images/pineapple.jpg',quantity: 1,},
  {id:"fruit-05",product: 'peach',price: 2,image: '/Images/peach.jpeg',quantity: 1,},
  {id:"fruit-06",product: 'grapes',price: 2.5,image: '/Images/grapes.jpeg',quantity: 1,},
  {id:"fruit-07",product: 'watermelon',price: 3,image: '/Images/watermelon.jpeg',quantity: 1,},
  {id:"fruit-08",product: 'strawberry',price: 3.5,image: '/Images/strawberry.jpeg',quantity: 1,},
  {id:"fruit-09",product: 'pear',price: 4,image: '/Images/pear.jpeg',quantity: 1,},
  {id:"fruit-10",product: 'kiwi',price: 4.5,image: '/Images/kiwi.jpeg',quantity: 1,},
  {id:"fruit-11",product: 'mango',price: 5,image: '/Images/mango.jpeg',quantity: 1,},
  {id:"fruit-12",product: 'papaya',price: 5.5,image: '/Images/papaya.jpeg',quantity: 1,},
  {id:"fruit-13",product: 'cherry',price: 6,image: '/Images/cherry.jpeg',quantity: 1,},  
  {id:"fruit-14",product: 'lemon',price: 7,image: '/Images/lemon.jpeg',quantity: 1,},
  {id:"fruit-15",product: 'coconut',price: 7.5,image: '/Images/coconut.jpeg',quantity: 1,},  
];